# Generated by Django 5.2.3 on 2025-07-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reciever',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
