# Generated by Django 5.1.5 on 2025-02-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_album_album_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='Rating',
        ),
    ]
